# Generated by Django 3.2.4 on 2022-03-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220321_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flan',
            old_name='is_pivate',
            new_name='is_private',
        ),
    ]
